cursovaya/foto_blog/blog/urls.py
from django.urls import path
from .views import *
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', BlogIndex.as_view(), name='index'),
    path('blogs/', Blogs.as_view(), name='blogs'),
    path('post/<slug:post_slug>/', ShowPost.as_view(), name='post'),
    path('category/<slug:cat_slug>/', BlogCategory.as_view(), name='category'),
    path('addpost/', AddPost.as_view(), name='addpost'),
    path('login/', LoginUser.as_view(), name='login'),
    path('logout/', LogoutUser.as_view(), name='logout'),
    path('addimg/', AddImg.as_view(), name='addimg'),
]

cursovaya/foto_blog/foto_blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cursovaya/foto_blog/blog/models.py
from django.db import models
from django.urls import reverse


class Blog(models.Model):
    title = models.CharField(max_length=250, verbose_name="Название")
    slug = models.SlugField(max_length=260, unique=True, verbose_name="URL")
    body = models.TextField(blank=True, verbose_name="Контент")
    photo = models.ImageField(upload_to="photo/%Y/%m/%d/", blank=True, verbose_name="Фото")
    time_cre = models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")
    time_up = models.DateTimeField(auto_now=True, verbose_name="Дата обновления")
    published = models.BooleanField(default=True, verbose_name="Публикация")
    cat = models.ForeignKey("Category", on_delete=models.PROTECT,
                            verbose_name="Категория")

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('post', kwargs={'post_slug': self.slug})

    class Meta:
        verbose_name = 'новость'
        verbose_name_plural = "Новости"
        ordering = ['-time_cre']


class Category(models.Model):
    name = models.CharField(max_length=200, verbose_name="Категория")
    slug = models.SlugField(max_length=250, unique=True, verbose_name="URL")

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('category', kwargs={'cat_slug': self.slug})

    class Meta:
        verbose_name = 'категорию'
        verbose_name_plural = "Категории"


class Photos(models.Model):
    image = models.ForeignKey(Blog, on_delete=models.CASCADE, verbose_name="картинки для блога", blank=True, null=True,
                              default=None)
    add_image = models.ImageField(upload_to="photo/%Y/%m/%d/add/", blank=True, null=True,
                                  verbose_name="Добавить картинку")

    class Meta:
        verbose_name = 'изображение'
        verbose_name_plural = "Изображения"

cursovaya/foto_blog/blog/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from .models import *


class LoginForm(AuthenticationForm):
    username = forms.CharField(label="Логин", widget=forms.TextInput(attrs={'class': 'form-input'}))
    password = forms.CharField(label="Пароль", widget=forms.PasswordInput(attrs={'class': 'form-input'}))

    class Meta:
        model = User
        fields = ('username', 'password')


class RegUserForm(UserCreationForm):
    username = forms.CharField(label="Логин", widget=forms.TextInput(attrs={'class': 'form-input'}))
    email = forms.EmailField(label="Email", widget=forms.EmailInput(attrs={'class': 'form-input'}))
    password1 = forms.CharField(label="Пароль", widget=forms.PasswordInput(attrs={'class': 'form-input'}))
    password2 = forms.CharField(label="Повтор пароля", widget=forms.PasswordInput(attrs={'class': 'form-input'}))

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')


class AddPostForms(forms.ModelForm):
    class Meta:
        model = Blog
        fields = ['title', 'slug', 'body', 'photo', 'published', 'cat']
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-input'}),
            'slug': forms.TextInput(attrs={'class': 'form-input'}),
            'body': forms.Textarea(attrs={'class': 'form-input'}),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['cat'].empty_label = "Категория не выбрана"

    def clean_title(self):
        title = self.cleaned_data['title']
        if len(title) > 200:
            raise ValidationError("Много символов")
        return title


class AddImgForms(forms.ModelForm):
    class Meta:
        model = Photos
        fields = ['image', 'add_image']

cursovaya/foto_blog/blog/views.py
from django.shortcuts import render, redirect
from django.views.generic import ListView, DetailView, CreateView
from .models import *
from django.urls import reverse_lazy
from .forms import *
from .utils import *
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login
from django.contrib.auth import logout
from .forms import LoginForm


class BlogIndex(DataMixin, CreateView):
    form_class = RegUserForm
    template_name = 'blog/index.html'
    success_url = reverse_lazy('login')

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        c_def = self.get_user_context(title="Регистрация")
        return dict(list(c_def.items()) + list(context.items()))

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return redirect('blogs')

    def get_queryset(self):
        return Blog.objects.filter(published=True).select_related('cat')


class Blogs(DataMixin, ListView):
    model = Blog
    template_name = "blog/blog.html"
    context_object_name = 'posts'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        c_def = self.get_user_context(title="Блог")
        return dict(list(c_def.items()) + list(context.items()))

    def get_queryset(self):
        return Blog.objects.filter(published=True).select_related('cat')


class ShowPost(DataMixin, DetailView):
    model = Blog
    template_name = "blog/post.html"
    slug_url_kwarg = "post_slug"
    context_object_name = "post"

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        c_def = self.get_user_context(title=context["post"])
        return dict(list(c_def.items()) + list(context.items()))


class BlogCategory(DataMixin, ListView):
    model = Blog
    template_name = "blog/blog.html"
    context_object_name = 'posts'

    def get_queryset(self):
        return Blog.objects.filter(cat__slug=self.kwargs['cat_slug'], published=True).select_related('cat')

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        c = Category.objects.get(slug=self.kwargs['cat_slug'])
        c_def = self.get_user_context(title="Категория - " + str(c.name), cat_selected=c.pk)
        return dict(list(c_def.items()) + list(context.items()))


class AddPost(LoginRequiredMixin, DataMixin, CreateView):
    form_class = AddPostForms
    template_name = 'blog/addpost.html'
    success_url = reverse_lazy('index')
    login_url = reverse_lazy('login')

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        c_def = self.get_user_context(title="Добавление статьи")
        return dict(list(c_def.items()) + list(context.items()))


class AddImg(LoginRequiredMixin, DataMixin, CreateView):
    form_class = AddImgForms
    template_name = 'blog/addimg.html'
    success_url = reverse_lazy('blogs')
    login_url = reverse_lazy('login')

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        c_def = self.get_user_context(title="Добавление картинки")
        return dict(list(c_def.items()) + list(context.items()))


class LoginUser(DataMixin, LoginView):
    form_class = LoginForm
    template_name = 'blog/login.html'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        c_def = self.get_user_context(title="Авторизация")
        return dict(list(c_def.items()) + list(context.items()))


class LogoutUser(DataMixin, ListView):
    def get(self, request, *args, **kwargs):
        logout(request)
        return redirect('blogs')

cursovaya/foto_blog/blog/templates/blog/addimg.html
{% extends 'blog/base.html' %}
{% load static %}
{% block content %}

<h1>{{ title }}</h1>

<form action="{% url 'addimg' %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}

    <div class="form-error">{{ form.not_field_error }}</div>

    {{ form.as_p }}
    <div class="cant">
        <button class="btn">Добавить</button>
    </div>
</form>
{% endblock %}

cursovaya/foto_blog/blog/templates/blog/addpost.html
{% extends 'blog/base.html' %}
{% load static %}
{% block content %}

<h1>{{ title }}</h1>

<form action="{% url 'addpost' %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}

    <div class="form-error">{{ form.not_field_error }}</div>

    {{ form.as_p }}
    <div class="cant">
        <button class="btn">Добавить</button>
    </div>
</form>
{% endblock %}

cursovaya/foto_blog/blog/templates/blog/base.html
<!DOCTYPE html>
{% load static %}
{% load blog_tags %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{title}}</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
<div class="header">
    <div class="wrap">
        <ul class="mainmenu">
            {% for m in menu %}
            <li class="first">
                <a href="{% url m.url %}">{{ m.title }}</a>
            </li>
            {% endfor %}
            {% if request.user.is_authenticated %}
            <li class="logout">
                {{ user.username }} | <a href="{% url 'logout' %}">Выйти</a>
            </li>
            {% else %}
            <li class="login">
                <a href="{% url 'index' %}">Регистрация</a>|
                <a href="{% url 'login' %}">Войти</a>
            </li>
            {% endif %}
        </ul>
    </div>
</div>
<div class="content">
    <div class="wrap">
        <div class="sidebar">
            <ul>
                {% if cat_sell == 0 %}
                <li class="selec">Все категории:</li>
                {% else %}
                <li><a href="{% url 'blogs' %}">Все категории:</a></li>
                {% endif %}

                {% show_cat cat_sell=cat_sell %}
            </ul>
        </div>
        <div class="main">
            {% block content %}
            {% endblock %}
            {% if page_obj.has_other_pages %}
            <div>
                <ul class="page">
                    {% if page_obj.has_previous %}
                    <li class="page-numm">
                        <a href="?page={{page_obj.previous_page_number}}">&lt;</a>
                    </li>
                    {% endif %}

                    {% for p in paginator.page_range %}
                    {% if page_obj.number == p %}
                    <li class="page-num page-num-sel">{{p}}</li>
                    {% elif p >= page_obj.number|add:-2 and p <= page_obj.number|add:2 %}
                    <li class="page-numm">
                        <a href="?page={{p}}">{{ p }}</a>
                    </li>
                    {% endif %}
                    {% endfor %}
                    {% if page_obj.has_next %}
                    <li class="page-numm">
                        <a href="?page={{page_obj.next_page_number}}">&gt;</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </div>
        {% endif %}
    </div>
</div>
</body>
</html>

cursovaya/foto_blog/blog/templates/blog/blog.html
{% extends 'blog/base.html' %}
{% load static %}
{% block content %}

<ul>
    {% for p in posts %}
    <li>
        <p class="first">Категория: {{ p.cat }}</p>
        <div class="text">
            {% if p.photo %}
            <img class="img" src="{{ p.photo.url }}" alt="">
            {% endif %}
            <h2><a href="{{ p.get_absolute_url }}">{{p.title}}</a></h2>
            <p>{{ p.body|truncatewords:49.5 }}</p>
        </div>
        <p class="data">дата: {{ p.time_up|date:"d-m-Y H:i:s" }}</p>
        <p class="user">автор: {{ user.username }}</p>
    </li>
    {% endfor %}
</ul>
{% endblock %}

cursovaya/foto_blog/blog/templates/blog/index.html
{% extends 'blog/base.html' %}
{% load static %}
{% block content %}
<h1 class="h">Приветствую вас на моей странице!)</h1><br>


{% if request.user.is_authenticated %}
{% else %}
<h2>{{ title }}:</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button class="btn">Регистрация</button>
</form>
{% endif %}
{% endblock %}

cursovaya/foto_blog/blog/templates/blog/list_cat.html
{% for c in cats %}
    {% if c.pk == cat_selected %}
    <li class="selected">{{ c.name }}</li>
    {% else %}
    <li><a href="{{ c.get_absolute_url }}">{{ c.name }}</a></li>
    {% endif %}
{% endfor %}

cursovaya/foto_blog/blog/templates/blog/login.html
{% extends 'blog/base.html' %}
{% load static %}
{% block content %}
<h1>{{ title }}:</h1>
<div class="reg">
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button class="btn">Войти</button>
    <p>Если не зарегистрированы то пройдите по ссылке<a href="{% url 'index' %}" class="rega">Зарегистрироваться</a></p>
</form>
</div>
{% endblock %}

cursovaya/foto_blog/blog/templates/blog/logout.html
{% extends 'blog/base.html' %}
{% load static %}
{% block content %}
<div class="logout">
    <h2>Пока!)</h2>
    <a href="{% url 'login' %}">Возвращайся снова)</a>
</div>
{% endblock %}

cursovaya/foto_blog/blog/templates/blog/post.html
{% extends 'blog/base.html' %}

{% block content %}
<div class="post">
    {% if post.photo %}
    <img class="img" src="{{ post.photo.url }}" alt="">
    {% endif %}
    {{ post.title }}
    <p>{{ post.body}}</p>
    {% for img in post.photos_set.all %}
    <img class="imagimage" src="{{ img.add_image.url }}">
    {% endfor %}
</div>
{% endblock %}